import { useEffect } from "react";
import "./modal.scss";

export const Modal = ({ closeModal }) => {
  return (
    <div className="modal">
      <button className="modal__close" onClick={closeModal}>
        X
      </button>
      <div className="modal__content">
        <div>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsam
          possimus nesciunt expedita unde necessitatibus laboriosam esse,
          obcaecati earum quia soluta recusandae nemo eius aspernatur quasi
          cupiditate magnam impedit nulla commodi!
        </div>
        <div>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora, dignissimos! Aut ipsum hic at. Eligendi quos reiciendis iste dolores cupiditate, assumenda dicta voluptatum obcaecati temporibus deleniti. Sed quibusdam accusamus officiis voluptatum quam, recusandae culpa cumque obcaecati, laborum non iusto nemo iste. Adipisci doloremque quam eaque dolore doloribus ab iusto veniam eum, fugiat quae quidem saepe rem similique fugit, tempore pariatur.
        </div>
        <div>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur distinctio ad harum quos? Quae voluptatum necessitatibus aspernatur est commodi. Architecto nostrum impedit vitae magni eligendi, labore similique nobis vel veritatis, veniam voluptate, fugit doloribus consequuntur totam inventore nesciunt perferendis temporibus repudiandae ipsam. Temporibus fugit vitae repudiandae ab impedit maiores ut non. Ipsa, magni accusamus quaerat error vitae esse dolor quo cumque ducimus, dicta molestias. Modi nobis rerum adipisci delectus non facere dolores eligendi facilis animi. Nobis autem exercitationem quos iure perferendis distinctio eligendi velit veniam cupiditate minus perspiciatis illo, doloremque earum, recusandae reprehenderit quis facere? Quo excepturi, dolore amet, expedita voluptatem necessitatibus quos reiciendis aperiam cumque pariatur obcaecati. Cum unde fugiat praesentium earum deleniti vitae impedit fuga dolorem consequatur alias nihil optio quaerat veniam, recusandae temporibus molestias dolor in perspiciatis quis eaque accusantium. Autem natus aspernatur quis laboriosam animi molestiae sequi! Laborum dignissimos, fugiat maxime illo odit accusantium voluptatem dolores ipsum quae tenetur culpa excepturi earum blanditiis sequi, ducimus asperiores, architecto voluptates libero ipsam odio? Voluptatum dignissimos rerum id dolore! Consequatur officiis, cumque voluptate nostrum odio enim similique voluptas amet sint voluptatem totam soluta iure recusandae voluptatibus explicabo optio quis nemo nisi facilis consequuntur consectetur voluptates incidunt sit? Ratione facilis distinctio, eius quas quam corporis ad dolor itaque. Provident perspiciatis ex aliquam, fuga optio enim unde totam? Assumenda libero quisquam tempore. Inventore, at sequi quam consequatur dignissimos adipisci. Quo enim deserunt optio rerum tenetur eius sint aliquid, ullam illo aut necessitatibus, soluta fugit repellendus dolores doloribus distinctio cum accusantium, aperiam iure quod autem exercitationem? Dicta minima, cumque eaque quas eos similique amet, facilis architecto reiciendis, perspiciatis id repudiandae optio provident. Est eos ex reprehenderit earum! Aliquid consequatur, sit quasi sunt repellat deleniti optio quaerat reiciendis corrupti. Fuga error dignissimos, unde esse odit quia hic quidem. Sequi architecto praesentium tempore amet nisi quibusdam similique! Numquam molestiae asperiores eum eve
        </div>
        <div>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur distinctio ad harum quos? Quae voluptatum necessitatibus aspernatur est commodi. Architecto nostrum impedit vitae magni eligendi, labore similique nobis vel veritatis, veniam voluptate, fugit doloribus consequuntur totam inventore nesciunt perferendis temporibus repudiandae ipsam. Temporibus fugit vitae repudiandae ab impedit maiores ut non. Ipsa, magni accusamus quaerat error vitae esse dolor quo cumque ducimus, dicta molestias. Modi nobis rerum adipisci delectus non facere dolores eligendi facilis animi. Nobis autem exercitationem quos iure perferendis distinctio eligendi velit veniam cupiditate minus perspiciatis illo, doloremque earum, recusandae reprehenderit quis facere? Quo excepturi, dolore amet, expedita voluptatem necessitatibus quos reiciendis aperiam cumque pariatur obcaecati. Cum unde fugiat praesentium earum deleniti vitae impedit fuga dolorem consequatur alias nihil optio quaerat veniam, recusandae temporibus molestias dolor in perspiciatis quis eaque accusantium. Autem natus aspernatur quis laboriosam animi molestiae sequi! Laborum dignissimos, fugiat maxime illo odit accusantium voluptatem dolores ipsum quae tenetur culpa excepturi earum blanditiis sequi, ducimus asperiores, architecto voluptates libero ipsam odio? Voluptatum dignissimos rerum id dolore! Consequatur officiis, cumque voluptate nostrum odio enim similique voluptas amet sint voluptatem totam soluta iure recusandae voluptatibus explicabo optio quis nemo nisi facilis consequuntur consectetur voluptates incidunt sit? Ratione facilis distinctio, eius quas quam corporis ad dolor itaque. Provident perspiciatis ex aliquam, fuga optio enim unde totam? Assumenda libero quisquam tempore. Inventore, at sequi quam consequatur dignissimos adipisci. Quo enim deserunt optio rerum tenetur eius sint aliquid, ullam illo aut necessitatibus, soluta fugit repellendus dolores doloribus distinctio cum accusantium, aperiam iure quod autem exercitationem? Dicta minima, cumque eaque quas eos similique amet, facilis architecto reiciendis, perspiciatis id repudiandae optio provident. Est eos ex reprehenderit earum! Aliquid consequatur, sit quasi sunt repellat deleniti optio quaerat reiciendis corrupti. Fuga error dignissimos, unde esse odit quia hic quidem. Sequi architecto praesentium tempore amet nisi quibusdam similique! Numquam molestiae asperiores eum eve
        </div>
         <div>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur distinctio ad harum quos? Quae voluptatum necessitatibus aspernatur est commodi. Architecto nostrum impedit vitae magni eligendi, labore similique nobis vel veritatis, veniam voluptate, fugit doloribus consequuntur totam inventore nesciunt perferendis temporibus repudiandae ipsam. Temporibus fugit vitae repudiandae ab impedit maiores ut non. Ipsa, magni accusamus quaerat error vitae esse dolor quo cumque ducimus, dicta molestias. Modi nobis rerum adipisci delectus non facere dolores eligendi facilis animi. Nobis autem exercitationem quos iure perferendis distinctio eligendi velit veniam cupiditate minus perspiciatis illo, doloremque earum, recusandae reprehenderit quis facere? Quo excepturi, dolore amet, expedita voluptatem necessitatibus quos reiciendis aperiam cumque pariatur obcaecati. Cum unde fugiat praesentium earum deleniti vitae impedit fuga dolorem consequatur alias nihil optio quaerat veniam, recusandae temporibus molestias dolor in perspiciatis quis eaque accusantium. Autem natus aspernatur quis laboriosam animi molestiae sequi! Laborum dignissimos, fugiat maxime illo odit accusantium voluptatem dolores ipsum quae tenetur culpa excepturi earum blanditiis sequi, ducimus asperiores, architecto voluptates libero ipsam odio? Voluptatum dignissimos rerum id dolore! Consequatur officiis, cumque voluptate nostrum odio enim similique voluptas amet sint voluptatem totam soluta iure recusandae voluptatibus explicabo optio quis nemo nisi facilis consequuntur consectetur voluptates incidunt sit? Ratione facilis distinctio, eius quas quam corporis ad dolor itaque. Provident perspiciatis ex aliquam, fuga optio enim unde totam? Assumenda libero quisquam tempore. Inventore, at sequi quam consequatur dignissimos adipisci. Quo enim deserunt optio rerum tenetur eius sint aliquid, ullam illo aut necessitatibus, soluta fugit repellendus dolores doloribus distinctio cum accusantium, aperiam iure quod autem exercitationem? Dicta minima, cumque eaque quas eos similique amet, facilis architecto reiciendis, perspiciatis id repudiandae optio provident. Est eos ex reprehenderit earum! Aliquid consequatur, sit quasi sunt repellat deleniti optio quaerat reiciendis corrupti. Fuga error dignissimos, unde esse odit quia hic quidem. Sequi architecto praesentium tempore amet nisi quibusdam similique! Numquam molestiae asperiores eum eve
        </div>
        <div>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur distinctio ad harum quos? Quae voluptatum necessitatibus aspernatur est commodi. Architecto nostrum impedit vitae magni eligendi, labore similique nobis vel veritatis, veniam voluptate, fugit doloribus consequuntur totam inventore nesciunt perferendis temporibus repudiandae ipsam. Temporibus fugit vitae repudiandae ab impedit maiores ut non. Ipsa, magni accusamus quaerat error vitae esse dolor quo cumque ducimus, dicta molestias. Modi nobis rerum adipisci delectus non facere dolores eligendi facilis animi. Nobis autem exercitationem quos iure perferendis distinctio eligendi velit veniam cupiditate minus perspiciatis illo, doloremque earum, recusandae reprehenderit quis facere? Quo excepturi, dolore amet, expedita voluptatem necessitatibus quos reiciendis aperiam cumque pariatur obcaecati. Cum unde fugiat praesentium earum deleniti vitae impedit fuga dolorem consequatur alias nihil optio quaerat veniam, recusandae temporibus molestias dolor in perspiciatis quis eaque accusantium. Autem natus aspernatur quis laboriosam animi molestiae sequi! Laborum dignissimos, fugiat maxime illo odit accusantium voluptatem dolores ipsum quae tenetur culpa excepturi earum blanditiis sequi, ducimus asperiores, architecto voluptates libero ipsam odio? Voluptatum dignissimos rerum id dolore! Consequatur officiis, cumque voluptate nostrum odio enim similique voluptas amet sint voluptatem totam soluta iure recusandae voluptatibus explicabo optio quis nemo nisi facilis consequuntur consectetur voluptates incidunt sit? Ratione facilis distinctio, eius quas quam corporis ad dolor itaque. Provident perspiciatis ex aliquam, fuga optio enim unde totam? Assumenda libero quisquam tempore. Inventore, at sequi quam consequatur dignissimos adipisci. Quo enim deserunt optio rerum tenetur eius sint aliquid, ullam illo aut necessitatibus, soluta fugit repellendus dolores doloribus distinctio cum accusantium, aperiam iure quod autem exercitationem? Dicta minima, cumque eaque quas eos similique amet, facilis architecto reiciendis, perspiciatis id repudiandae optio provident. Est eos ex reprehenderit earum! Aliquid consequatur, sit quasi sunt repellat deleniti optio quaerat reiciendis corrupti. Fuga error dignissimos, unde esse odit quia hic quidem. Sequi architecto praesentium tempore amet nisi quibusdam similique! Numquam molestiae asperiores eum eve
        </div>
         <div>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur distinctio ad harum quos? Quae voluptatum necessitatibus aspernatur est commodi. Architecto nostrum impedit vitae magni eligendi, labore similique nobis vel veritatis, veniam voluptate, fugit doloribus consequuntur totam inventore nesciunt perferendis temporibus repudiandae ipsam. Temporibus fugit vitae repudiandae ab impedit maiores ut non. Ipsa, magni accusamus quaerat error vitae esse dolor quo cumque ducimus, dicta molestias. Modi nobis rerum adipisci delectus non facere dolores eligendi facilis animi. Nobis autem exercitationem quos iure perferendis distinctio eligendi velit veniam cupiditate minus perspiciatis illo, doloremque earum, recusandae reprehenderit quis facere? Quo excepturi, dolore amet, expedita voluptatem necessitatibus quos reiciendis aperiam cumque pariatur obcaecati. Cum unde fugiat praesentium earum deleniti vitae impedit fuga dolorem consequatur alias nihil optio quaerat veniam, recusandae temporibus molestias dolor in perspiciatis quis eaque accusantium. Autem natus aspernatur quis laboriosam animi molestiae sequi! Laborum dignissimos, fugiat maxime illo odit accusantium voluptatem dolores ipsum quae tenetur culpa excepturi earum blanditiis sequi, ducimus asperiores, architecto voluptates libero ipsam odio? Voluptatum dignissimos rerum id dolore! Consequatur officiis, cumque voluptate nostrum odio enim similique voluptas amet sint voluptatem totam soluta iure recusandae voluptatibus explicabo optio quis nemo nisi facilis consequuntur consectetur voluptates incidunt sit? Ratione facilis distinctio, eius quas quam corporis ad dolor itaque. Provident perspiciatis ex aliquam, fuga optio enim unde totam? Assumenda libero quisquam tempore. Inventore, at sequi quam consequatur dignissimos adipisci. Quo enim deserunt optio rerum tenetur eius sint aliquid, ullam illo aut necessitatibus, soluta fugit repellendus dolores doloribus distinctio cum accusantium, aperiam iure quod autem exercitationem? Dicta minima, cumque eaque quas eos similique amet, facilis architecto reiciendis, perspiciatis id repudiandae optio provident. Est eos ex reprehenderit earum! Aliquid consequatur, sit quasi sunt repellat deleniti optio quaerat reiciendis corrupti. Fuga error dignissimos, unde esse odit quia hic quidem. Sequi architecto praesentium tempore amet nisi quibusdam similique! Numquam molestiae asperiores eum eve
        </div>
        
      </div>
    </div>
  );
};
